name: smartcvmatcher
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.9
  - pip
  - pip:
    - sentence-transformers
    - scikit-learn
    - streamlit
    - pandas
    - joblib
    - xgboost
    - numpy
    - yaml
    - requests

