name: smartcvmatcher
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly  # à enlever si GPU disponible
  - pip:
    - sentence-transformers
    - scikit-learn
    - streamlit
    - pandas
    - joblib
